polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'

urlpatterns=[
path('',views.index,name='index'),
path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
   path('xxx/', views.xxx, name='xxx'),
]

tedj/urls.py
from django.contrib import admin
#from django.urls import path
from django.urls import include, path
#import xadmin
#xadmin.autodiscover()
#import xadmin
#xadmin.autodiscover()
#url(r'^admin/', include(xadmin.site.urls)),

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
 #   url('xadmin/', include(xadmin.site.urls)),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class Question(models.Model):
    
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    class Meta:
        #末尾不加s
        verbose_name_plural='标签'
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    def __str__(self):
        return self.question_text   
 
     


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0) 
    class Meta:
        #末尾不加s
        verbose_name_plural='数据'
    def __str__(self):
        return self.choice_text
        
        
class user(models.Model):
    username = models.CharField(max_length=200,primary_key=True)
    pwd = models.CharField(max_length=200)
    email=models.CharField(max_length=200)
    time=models.DateTimeField('date published')
    def __str__(self):
        return self.username

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic.base import View
from .models import Choice, Question,user
import uuid,datetime
#from django.template import loader
# Create your views here.
def index(request):
     # return HttpResponse('hello word')
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
   # template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/index.html', context)
  #  return HttpResponse(template.render(context, request))
  
def detail(request, question_id):
  #  return HttpResponse("You're looking at question %s." % question_id)
  '''
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})
  '''
  question = get_object_or_404(Question, pk=question_id)
  return render(request, 'polls/detail.html', {'question': question})
'''
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)
'''
def xxx(request):
      # return HttpResponse('xxx')
       if request.method=='GET':     
           return render(request,'polls/xxx.html')       
       if request.method=='POST':
           username=request.POST['username']
           email=request.POST['email']
           password=request.POST['pwd']
           
           b=user.objects.create(username=username,email=email,pwd=password,time= datetime.datetime.now())
        #   return render(request,'polls/xxx.html')
           return HttpResponse(request.POST['username'])
           
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})



def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="投票" />
</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>菜鸟教程(runoob.com)</title>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />


</head>
<body>
  


<h1>Hello Django</h1>



{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
     <h2>标题:  {{question}}</h2>
     
       <!--
       <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
      -->
       <h3> <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li></h3>
    <br>
    <br>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/xxx.html
<center>
<h1>
<form action="{% url 'polls:xxx' %}" method="post">
{% csrf_token %}
<input name="username"  />
<input name="email" />
<input name="pwd" />


<input type="submit" value="提交" />





</form>
</h1>
</center>